export const DATA_STATE = {
  NOT_INITIALIZED: "NOT_INITIALIZED",
  FETCHING: "FETCHING",
  SENDING: "SENDING",
  INITIALIZED: "INITIALIZED",
  FETCHED_FAILED: "FETCHED_FAILED",
  SEND_FAILED: "SEND_FAILED",
  PERSISTED: "PERSISTED",
  SEND_SUCCESS: "SEND_SUCCESS",
  FETCH_SUCCESS: "FETCH_SUCCESS",
};
